name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t binary-tree-performance .

      - name: Run Docker container
        run: docker run -d -p 8080:80 binary-tree-performance
