name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      run: |
        docker login --username cara1910 --password ${{secrets.PAROLA}} ghcr.io
        docker build . --tag ghcr.io/cara1910/proiect_map_18:latest
        docker push ghcr.io/cara1910/proiectmap