name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # sau master, în funcție de cum se numește ramura principală

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: "caracook1e"  # Înlocuiește cu username-ul tău DockerHub
        password: "PAROLAdocker1"  # Înlocuiește cu parola ta DockerHub (sau token-ul de acces)

    - name: Build Docker image
      run: |
        docker build -t caracook1e/proiect_map_18:latest .

    - name: Push Docker image
      run: |
        docker push caracook1e/proiect_map_18:latest
